/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StructuredRouteImport } from './routes/structured'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const StructuredRoute = StructuredRouteImport.update({
  id: '/structured',
  path: '/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaign': typeof CampaignRoute
  '/canvas': typeof CanvasRoute
  '/roi': typeof RoiRoute
  '/structured': typeof StructuredRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaign': typeof CampaignRoute
  '/canvas': typeof CanvasRoute
  '/roi': typeof RoiRoute
  '/structured': typeof StructuredRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaign': typeof CampaignRoute
  '/canvas': typeof CanvasRoute
  '/roi': typeof RoiRoute
  '/structured': typeof StructuredRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/campaign'
    | '/canvas'
    | '/roi'
    | '/structured'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/campaign' | '/canvas' | '/roi' | '/structured'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/campaign'
    | '/canvas'
    | '/roi'
    | '/structured'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignRoute: typeof CampaignRoute
  CanvasRoute: typeof CanvasRoute
  RoiRoute: typeof RoiRoute
  StructuredRoute: typeof StructuredRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/structured': {
      id: '/structured'
      path: '/structured'
      fullPath: '/structured'
      preLoaderRoute: typeof StructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampaignRoute: CampaignRoute,
  CanvasRoute: CanvasRoute,
  RoiRoute: RoiRoute,
  StructuredRoute: StructuredRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
