/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StructuredRouteImport } from './routes/structured'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as OtaRouteImport } from './routes/ota'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OtaIndexRouteImport } from './routes/ota.index'
import { Route as OtaOfferRouteImport } from './routes/ota.offer'
import { Route as OtaJourneyRouteImport } from './routes/ota.journey'

const StructuredRoute = StructuredRouteImport.update({
  id: '/structured',
  path: '/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const OtaRoute = OtaRouteImport.update({
  id: '/ota',
  path: '/ota',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OtaIndexRoute = OtaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OtaRoute,
} as any)
const OtaOfferRoute = OtaOfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => OtaRoute,
} as any)
const OtaJourneyRoute = OtaJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => OtaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaign': typeof CampaignRoute
  '/canvas': typeof CanvasRoute
  '/ota': typeof OtaRouteWithChildren
  '/roi': typeof RoiRoute
  '/structured': typeof StructuredRoute
  '/ota/journey': typeof OtaJourneyRoute
  '/ota/offer': typeof OtaOfferRoute
  '/ota/': typeof OtaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaign': typeof CampaignRoute
  '/canvas': typeof CanvasRoute
  '/roi': typeof RoiRoute
  '/structured': typeof StructuredRoute
  '/ota/journey': typeof OtaJourneyRoute
  '/ota/offer': typeof OtaOfferRoute
  '/ota': typeof OtaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaign': typeof CampaignRoute
  '/canvas': typeof CanvasRoute
  '/ota': typeof OtaRouteWithChildren
  '/roi': typeof RoiRoute
  '/structured': typeof StructuredRoute
  '/ota/journey': typeof OtaJourneyRoute
  '/ota/offer': typeof OtaOfferRoute
  '/ota/': typeof OtaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/campaign'
    | '/canvas'
    | '/ota'
    | '/roi'
    | '/structured'
    | '/ota/journey'
    | '/ota/offer'
    | '/ota/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/campaign'
    | '/canvas'
    | '/roi'
    | '/structured'
    | '/ota/journey'
    | '/ota/offer'
    | '/ota'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/campaign'
    | '/canvas'
    | '/ota'
    | '/roi'
    | '/structured'
    | '/ota/journey'
    | '/ota/offer'
    | '/ota/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignRoute: typeof CampaignRoute
  CanvasRoute: typeof CanvasRoute
  OtaRoute: typeof OtaRouteWithChildren
  RoiRoute: typeof RoiRoute
  StructuredRoute: typeof StructuredRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/structured': {
      id: '/structured'
      path: '/structured'
      fullPath: '/structured'
      preLoaderRoute: typeof StructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ota': {
      id: '/ota'
      path: '/ota'
      fullPath: '/ota'
      preLoaderRoute: typeof OtaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ota/': {
      id: '/ota/'
      path: '/'
      fullPath: '/ota/'
      preLoaderRoute: typeof OtaIndexRouteImport
      parentRoute: typeof OtaRoute
    }
    '/ota/offer': {
      id: '/ota/offer'
      path: '/offer'
      fullPath: '/ota/offer'
      preLoaderRoute: typeof OtaOfferRouteImport
      parentRoute: typeof OtaRoute
    }
    '/ota/journey': {
      id: '/ota/journey'
      path: '/journey'
      fullPath: '/ota/journey'
      preLoaderRoute: typeof OtaJourneyRouteImport
      parentRoute: typeof OtaRoute
    }
  }
}

interface OtaRouteChildren {
  OtaJourneyRoute: typeof OtaJourneyRoute
  OtaOfferRoute: typeof OtaOfferRoute
  OtaIndexRoute: typeof OtaIndexRoute
}

const OtaRouteChildren: OtaRouteChildren = {
  OtaJourneyRoute: OtaJourneyRoute,
  OtaOfferRoute: OtaOfferRoute,
  OtaIndexRoute: OtaIndexRoute,
}

const OtaRouteWithChildren = OtaRoute._addFileChildren(OtaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampaignRoute: CampaignRoute,
  CanvasRoute: CanvasRoute,
  OtaRoute: OtaRouteWithChildren,
  RoiRoute: RoiRoute,
  StructuredRoute: StructuredRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
